# ===================================================
#      Morphius AI Backend - render.yaml (FINAL)
# ===================================================

envVarGroups:
  - name: morphius-secrets
    envVars:
      - key: POSTGRES_URL
        fromService:
          type: pserv
          # CRITICAL: This name must EXACTLY match your database service name on Render.
          name: morphius-db # <--- CHANGE THIS if your DB is named differently.
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: GMAIL_EMAIL
        sync: false
      - key: GMAIL_PASSWORD
        sync: false
      - key: CONTACTOUT_API_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.4

services:
  # -----------------
  # The PostgreSQL Database
  # -----------------
  - type: pserv
    # CRITICAL: This name must EXACTLY match the name used in `fromService` above.
    name: morphius-db # <--- CHANGE THIS if your DB is named differently.
    plan: free
    postgres:
      version: 14

  # -----------------
  # The Background Worker
  # -----------------
  - type: worker
    name: reply-processor
    plan: free
    env: python
    buildCommand: "pip install -r requirements.txt && python main.py setup-db"
    startCommand: "python main.py process-replies --daemon"
    envVarGroup: morphius-secrets # Use the shared environment group

  # -----------------
  # Cron Jobs
  # -----------------
  - type: cron
    name: daily-outreach
    plan: free
    schedule: "0 14 * * *"
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py send-outreach"
    envVarGroup: morphius-secrets

  - type: cron
    name: daily-automations
    plan: free
    schedule: "0 15 * * *"
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py run-automations"
    envVarGroup: morphius-secrets
